
demonstration:
  default_frame: 'base_link'
  robot_frame: 'base_link'
  reference_frames: ['KittingBox']
  base_frame: ''
  grasping_actions: ['pick']
  placing_actions: ['place']
  navigation_actions: ['']

genetic:
  n_generations: 100
  n_population: 32
  save_interval: 20
  ind_length: 4
  p_crossover: 0.25
  p_mutation: 0.75
  mutation_add: 0.1
  mutation_delete: 0.3
  mutations_per_individual: 3
  p_elite: 0.1
  selection: 'tournament'
  baseline_index: 1
  graphics: False

behavior_tree:
  tick_freq: 1.0

algoryx:
  ee_name: 'GripperControlBody'
  robot_name: 'RobotControlBody'
  random_bringup: False